# We will call a right angled triangle perfect if
#    1. it is a primitive right angled triangle
#    2. its hypotenuse is a perfect square
# We will call a right angled triangle super-perfect if
#    1. it is a perfect right angled triangle and
#    2. its area is a multiple of the perfect numbers 6 and 28
# How many perfect right-angled triangles with c \leq 10^{16}
# exist that are not super-perfect?
# ----------------------------------------------------
# Analysis: Euclid's formula
#           a = m^{2} - n^{2}, b = 2 m n, c = m^{2} + n^{2}
#           form a Pythagorean triple, where m > n > 0
#           The triple generated by Euclid's formula is primitive
#           if and only if m and n are coprime and not both odd
#           Since c should be a perfect square, we know that
#           m^{2} + n^{2} = k^{2}, which formed another primitive
#           Pythagorean triple
#           Let m = x^{2} - y^{2}, n = 2 x y, where x > y > 0,
#           x and y are coprime and not both odd
#           Thus, the area of a perfect right angled triangle has
#           the form of S = a b / 2 = 2 x y (x^{2} - y^{2}) (x^{4} + y^{4} - 6 x^{2} y^{2})
#           If we want S is a multiple of 6 and 28, we only need
#           S % 3 = 0, S % 4 = 0 and S % 7 = 0
#           Since x and y are not both odd, we can easily see that
#           S % 3 = 0 and S % 4 = 0
#           Now we only need to check whether S % 7 = 0
#           x \ y  1  2  3  4  5
#             2    0
#             3    0  0
#             4    0  0  0
#             5    0  0  0  0
#             6    0  0  0  0  0
#           Therefore, all perfect right angled triangles are super-perfect right angled triangles

0955aaba0b1fe9329db646c8ba525a34eb966c406ffe896f804b4a23b98abb97bee29dcdcfbfeb695cda618cb0b3b20faa82
8687d5efb5d7929f38d761ba9dc57e485688b7ba13874ded97979695931a02aeb67bf46db62d137bab299830b65bb4761461
beb4111d29e8a0af04513764d2d992b9c2846c3aa4dfe0cb729c16e75cac3a2c5225102287b29ca6cc08d9fd7d6ac449d1bf
11d0040dfb570967be7cb7471517185e83d2083739f01046060e446e6d6fc29743227e45c84ce298d6f85098e9467d799f15
691e6caa7c81d839c42360b75a23ef6241f171c741b7f1d065e07a86f252acbb86d0c1a42a216addf1b0f03988f65d2cb186
23c992aa2b65
