# We will call a right angled triangle perfect if
#    1. it is a primitive right angled triangle
#    2. its hypotenuse is a perfect square
# We will call a right angled triangle super-perfect if
#    1. it is a perfect right angled triangle and
#    2. its area is a multiple of the perfect numbers 6 and 28
# How many perfect right-angled triangles with c \leq 10^{16}
# exist that are not super-perfect?
# ----------------------------------------------------
# Analysis: Euclid's formula
#           a = m^{2} - n^{2}, b = 2 m n, c = m^{2} + n^{2}
#           form a Pythagorean triple, where m > n > 0
#           The triple generated by Euclid's formula is primitive
#           if and only if m and n are coprime and not both odd
#           Since c should be a perfect square, we know that
#           m^{2} + n^{2} = k^{2}, which formed another primitive
#           Pythagorean triple
#           Let m = x^{2} - y^{2}, n = 2 x y, where x > y > 0,
#           x and y are coprime and not both odd
#           Thus, the area of a perfect right angled triangle has
#           the form of S = a b / 2 = 2 x y (x^{2} - y^{2}) (x^{4} + y^{4} - 6 x^{2} y^{2})
#           If we want S is a multiple of 6 and 28, we only need
#           S % 3 = 0, S % 4 = 0 and S % 7 = 0
#           Since x and y are not both odd, we can easily see that
#           S % 3 = 0 and S % 4 = 0
#           Now we only need to check whether S % 7 = 0
#           x \ y  1  2  3  4  5
#             2    0
#             3    0  0
#             4    0  0  0
#             5    0  0  0  0
#             6    0  0  0  0  0
#           Therefore, all perfect right angled triangles are super-perfect right angled triangles

623bd799c6bfb36cb011098bd33f0dd37d36e32ffcf08221914506a793c988a904274447f086e507b73437eda358048d12adf9e2f4974cdea0a028c1b1882f41d722378f6ebe277aa3552ec2aaf68c7f60df84a014bbfadf856e31256a94834597ae2636f962f99b37659e8c6d2481996ea5ceda4a5bf9d88424e67fbe766b7c2738160601fbb2821dd0ff42f5dbcaa0e71bbcd6570d1dffee45e20aa0e2aa6984fae58154264feacdb39772ab1b677d499f23193dd013bce2cc318d7d2c5bc548fcbb11db8596b42e6cb8b5b5918bcb752d47192f759ec61ea7f78fe2a1b707b4a633f7678e087c6e4b56fa78228d52bfd2a62884176a635e41d31d35116f5a
